In [1]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [2]:
#creating tensors

scalar=tf.constant([5])
scalar

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In [3]:
#dimensions of tensor

In [4]:
scalar.ndim

1

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
#create a matrix
matrix=tf.constant([[12,150],[45,65]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 12, 150],
       [ 45,  65]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#another matrix
matrix1=tf.constant([[12,150],[45,65],[1,5]],dtype=tf.float16)
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 12., 150.],
       [ 45.,  65.],
       [  1.,   5.]], dtype=float16)>

In [10]:
matrix1.ndim

2

In [11]:
#creating a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],
                    [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
#tensorflow variable
changeble_tensor=tf.Variable([10,10])
unchangebale_tensor=tf.constant([10,10])
changeble_tensor,unchangebale_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [14]:
#changing the elements in changeble tensor
changeble_tensor[0].assign(7)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [16]:
#changing the elements in unchangeble tensor
unchangebale_tensor[0].assign(7)
unchangebale_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [17]:
#creating random tensor
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.uniform(shape=(3,2))

random_2==random_1

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [18]:
#shuffle order of images
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [19]:
tf.random.set_seed(2)
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [20]:
#tf.random.set_seed(2)
tf.random.shuffle(not_shuffled,seed=56)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
tf.random.set_seed(2)
tf.random.shuffle(not_shuffled,seed=56)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [22]:
#other ways to create tensors
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros([23,56])

<tf.Tensor: shape=(23, 56), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [24]:
#we can also convert numpy array into tensor


In [25]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
#first 2 elements of each dimension
rank_4_tensor[:2,:2,:1,:2]

<tf.Tensor: shape=(2, 2, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]]],


       [[[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[:1,:1,:1,:2]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor[:1,:,:1,:2]

<tf.Tensor: shape=(1, 3, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [29]:
rank_2_tensor=tf.constant([[12,45],[15,89]])

In [30]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 45],
       [15, 89]], dtype=int32)>

In [31]:
#reshaping tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([45, 89], dtype=int32)>

In [32]:
#converting the rank 2 to rank 3
rank_new_tensor=rank_2_tensor[...,tf.newaxis]
rank_new_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [45]],

       [[15],
        [89]]], dtype=int32)>

In [33]:
new_tensor=tf.expand_dims(
    rank_2_tensor,axis=1
)

In [34]:
new_tensor.ndim,new_tensor.shape

(3, TensorShape([2, 1, 2]))

In [35]:
new_tensor=tf.expand_dims(
    rank_2_tensor,axis=0
)

In [36]:
new_tensor.ndim,new_tensor.shape

(3, TensorShape([1, 2, 2]))

In [37]:
new_tensor=tf.expand_dims(
    rank_2_tensor,axis=-1
)
new_tensor.ndim,new_tensor.shape

(3, TensorShape([2, 2, 1]))

In [38]:
#manipulating tensors ie pattern discovery

#basic operation
basic_tensor=tf.constant([[12,45],[15,89]])
basic_tensor+10
basic_tensor*10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 450],
       [150, 890]], dtype=int32)>

In [39]:
tf.add(basic_tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 55],
       [25, 99]], dtype=int32)>

In [40]:
tf.multiply(basic_tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[120, 450],
       [150, 890]], dtype=int32)>

In [41]:
#matrix multiplications

basic_tensor1=tf.constant([[12,45],[15,89]])
basic_tensor2=tf.constant([[10],[11]])

tf.matmul(basic_tensor1,basic_tensor2)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 615],
       [1129]], dtype=int32)>

In [42]:
basic_tensor@basic_tensor2

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 615],
       [1129]], dtype=int32)>

In [43]:
tf.reshape(basic_tensor,shape=(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[12, 45, 15, 89]], dtype=int32)>

In [44]:
basic_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 45],
       [15, 89]], dtype=int32)>

In [45]:
tf.transpose(basic_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 15],
       [45, 89]], dtype=int32)>

In [46]:
#dot product
tf.tensordot(basic_tensor1,basic_tensor2,axes=1)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 615],
       [1129]], dtype=int32)>

In [47]:
##changing the datatype of the tensor
basic_tensor.dtype

tf.int32

In [48]:
basic_tensor=tf.cast(basic_tensor,dtype=tf.float64)

In [49]:
basic_tensor.dtype

tf.float64

In [54]:
#tensor aggregation

import numpy as np
tensor=tf.constant(np.random.randint(0,100,size=50))
tensor


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([33,  0, 91,  5, 73, 53, 31, 40, 72, 41, 47, 44,  5,  6, 46, 26,  2,
       34, 75, 18,  7, 74, 68, 55,  6,  5, 75, 73, 71, 93,  2, 53, 52, 66,
       79, 83,  6, 54, 19, 84, 26,  2, 18, 20, 58, 59, 86, 30, 23, 55])>

In [55]:
tf.reduce_min(tensor),tf.reduce_max(tensor),tf.reduce_mean(tensor)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=93>,
 <tf.Tensor: shape=(), dtype=int64, numpy=42>)

In [56]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2144>

In [61]:
import tensorflow_probability as tfp
print(tfp.stats.variance(tensor))
#tf.math.reduce_variance(tensor)
#it doesnt work since it requires real or complex number so....
tf.math.reduce_std(tf.cast(tensor,dtype=tf.float16))

tf.Tensor(810, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=float16, numpy=28.453125>

In [63]:
tf.argmax(tensor)
#intution behind the positional maximum and minimum
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [65]:
tensor[tf.argmin(tensor)]==tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [70]:
#tensor squuezing
tf.random.set_seed(42)
tensor_unsqu=tf.constant(tf.random.normal(shape=(1,1,1,1,50)))
tensor_unsqu

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 ,
           -2.3880599 , -1.0392479 , -0.5573232 ,  0.539707  ,
            1.6994323 ,  0.28893656, -1.5066116 , -0.26454744,
           -0.59722406, -1.9171132 , -0.62044144,  0.8504023 ,
           -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
           -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,
            0.77852213, -0.47338897,  0.97772694,  0.24694404,
            0.20573747, -0.5256233 ,  0.32410017,  0.02545409,
           -0.10638497, -0.6369475 ,  1.1603122 ,  0.2507359 ,
           -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
           -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 ,
           -0.56668764, -0.35819843,  0.88698626,  0.5274477 ,
            0.70402247, -0.33421248]]]]], dtype=float32)>

In [73]:
tensor_seq=tf.squeeze(tensor_unsqu)

In [74]:
tensor_seq
#it removes all the single dimension from tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.3274685 , -0.8426258 ,  0.3194337 , -1.4075519 , -2.3880599 ,
       -1.0392479 , -0.5573232 ,  0.539707  ,  1.6994323 ,  0.28893656,
       -1.5066116 , -0.26454744, -0.59722406, -1.9171132 , -0.62044144,
        0.8504023 , -0.40604794, -3.0258412 ,  0.9058464 ,  0.29855987,
       -0.22561555, -0.7616443 , -1.891714  , -0.9384712 ,  0.77852213,
       -0.47338897,  0.97772694,  0.24694404,  0.20573747, -0.5256233 ,
        0.32410017,  0.02545409, -0.10638497, -0.6369475 ,  1.1603122 ,
        0.2507359 , -0.41728497,  0.40125778, -1.4145442 , -0.59318566,
       -1.6617213 ,  0.33567193,  0.10815629,  0.2347968 , -0.56668764,
       -0.35819843,  0.88698626,  0.5274477 ,  0.70402247, -0.33421248],
      dtype=float32)>

In [84]:
#one hot encoding
#a=['blue','green','red']
a=[0,1,2,3]
tf.one_hot(a,depth=4,on_value="HEY WELCOME TO MY GITHUB,I KNOW YOU SAW ME",off_value='0')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'HEY WELCOME TO MY GITHUB,I KNOW YOU SAW ME', b'0', b'0', b'0'],
       [b'0', b'HEY WELCOME TO MY GITHUB,I KNOW YOU SAW ME', b'0', b'0'],
       [b'0', b'0', b'HEY WELCOME TO MY GITHUB,I KNOW YOU SAW ME', b'0'],
       [b'0', b'0', b'0', b'HEY WELCOME TO MY GITHUB,I KNOW YOU SAW ME']],
      dtype=object)>

In [85]:
tf.one_hot(a,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [87]:
#square, log and aquare root
tensor_new=tf.range(1,10)
tf.square(tensor_new)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [92]:
tf.sqrt(tf.cast(tensor_new,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [96]:
tf.math.log(tf.cast(tensor_new,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [ ]:
#tensors and numpy
#tensor flow and numpy are interoperable and numpy is build on numpy arrays
#we can convert them vice versa
